# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci --legacy-peer-deps
    - name: Fetch all branches
      run: git fetch --all
    - name: Get base commit hash
      id: base
      run: echo "::set-output name=BASE_COMMIT::$(git rev-parse origin/main)"
    - name: Get head commit hash
      id: head
      run: echo "::set-output name=HEAD_COMMIT::$(git rev-parse HEAD)"
    - run: npx nx affected --target=build --base=${{ steps.base.outputs.BASE_COMMIT }} --head=${{ steps.head.outputs.HEAD_COMMIT }}
    - run: npx nx affected --target=test --base=${{ steps.base.outputs.BASE_COMMIT }} --head=${{ steps.head.outputs.HEAD_COMMIT }}
